[versions]
agp = "8.8.2"

core = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.0"
navigation = "2.8.5"

junitJupiter = "5.10.2"

androidxJunit = "1.2.1"
espresso = "3.6.1"
testCore = "1.6.1"
testRunner = "1.6.2"
testRules = "1.6.1"

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "testCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
